ALTER PROC SP_WORKER_INOUT_DENEME
@WORKERBARCODE AS VARCHAR(50),
@DATE AS DATETIME,
@IOTYPE AS VARCHAR(1),
@GATEID AS INT
AS
BEGIN
	DECLARE @WORKERNAME AS VARCHAR(100)
	DECLARE @WORKERID AS INT
	SELECT @WORKERNAME=WORKERNAME, @WORKERID=ID FROM WORKERS WHERE WORKERBARCODE=@WORKERBARCODE
	IF @WORKERID IS NULL
	BEGIN
		RAISERROR('OKUTULAN KART GECERSIZ',16,1)
		RETURN
	END

	DECLARE @LASTIO AS VARCHAR(1)

	SELECT TOP 1 @LASTIO=IOTYPE FROM WORKERTRANSACTIONS 
	WHERE WORKERID=1 AND DATE_>=CONVERT(DATE,GETDATE())
	ORDER BY DATE_ DESC

	IF @LASTIO=@IOTYPE
	BEGIN
		IF @IOTYPE='G'
		BEGIN
			RAISERROR('ZATEN ICERIDE GOZUKUYORSUNUZ',16,1)
			RETURN
		END
		IF @IOTYPE='C'
		BEGIN
			RAISERROR('ZATEN DISARIDA GOZUKUYORSUNUZ',16,1)
			RETURN
		END
		RETURN
	END
INSERT INTO WORKERTRANSACTIONS (WORKERID,DATE_,IOTYPE,GATEID)
VALUES (@WORKERID, @DATE, @IOTYPE, @GATEID)

SELECT @WORKERID AS WORKERID, @DATE AS DATE_, @IOTYPE AS IOTYPE, @GATEID AS GATEID
END

EXEC SP_WORKER_INOUT_DENEME
@WORKERBARCODE='7D53DB7F-2B73-41CB-93AB-98080D3109AC',
@DATE='2020-01-01',
@IOTYPE='G',
@GATEID=1

