SELECT * FROM CUSTOMER 
--CUSTOMER tablomuzda suan 4 kaydimiz var.

INSERT INTO 
CUSTOMER
([CUSTOMERNAME], [CITY], [DISTRICT], [BIRTHDATE], [GENDER]) 
VALUES 
('BURCU CANDAN', 'KOCAELÝ', 'MERKEZ', '1994-05-08', 'K')

