
---GUN BAZLI SATIS SAYILARI----

SELECT BRANCH AS SUBE, 
	   DATE_ AS TARIH, 
	   SUM(LINENET) AS TOPLAM_SATIS, 
	   COUNT(*) AS SATISSAYISI
FROM SALES
WHERE BRANCH='Ankara Subesi' --AND DATE_='2017-01-05'
GROUP BY BRANCH, DATE_
ORDER BY DATE_
--89 günlük satis verisi geldi. (3 aylik)