---- Urun Kategorilerine Gore Satis Rakamlari----
SELECT CATEGORY_NAME1, BRAND, SUM(LINENET) AS TOPLAM_SATIS_TUTARI FROM SALES
GROUP BY CATEGORY_NAME1, BRAND
ORDER BY SUM(LINENET) DESC

-- 2 basamakli
SELECT CATEGORY_NAME1, CATEGORY_NAME2, BRAND, SUM(LINENET) AS TOPLAM_SATIS_TUTARI
FROM SALES
GROUP BY CATEGORY_NAME1, CATEGORY_NAME2, BRAND
ORDER BY SUM(LINENET) DESC

-- 3 basamakli 
SELECT CATEGORY_NAME1, CATEGORY_NAME2, CATEGORY_NAME3, BRAND,
	   SUM(LINENET) AS TOPLAM_SATIS_TUTARI
FROM SALES
WHERE BRAND='ÜLKER'
GROUP BY CATEGORY_NAME1, CATEGORY_NAME2, CATEGORY_NAME3, BRAND
ORDER BY SUM(LINENET) DESC

