
--Bir kullanicinin yaptigi alisveris sayisi, adedi ve toplami
SELECT U.USERNAME_ ADSOYAD, COUNT(DISTINCT BD.BASKETID) ALISVERISSAYISI, 
	   COUNT(BD.ID) ALDIGI_URUN_SAYISI, 
	   SUM(BD.AMOUNT) ALDIGI_URUN_MIKTARI, SUM(TOTAL) ODEDIGI_UCRET
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
INNER JOIN ITEM I ON I.ID=BD.ID
INNER JOIN ORDER_ O ON O.BASKETID=B.ID
INNER JOIN ADDRES A ON A.ID=O.ADDRESSID
INNER JOIN CITY C ON C.ID=A.CITYID
INNER JOIN TOWN T ON T.ID=A.TOWNID
INNER JOIN DISTRICT D ON D.ID=A.DISTRICTID
INNER JOIN INVOICE INV ON INV.ORDERID=O.ID
GROUP BY U.USERNAME_


--Hangi sehirde ne kadar alisveris yapildi
SELECT C.CITY SEHIR, COUNT(DISTINCT BD.BASKETID) ALISVERISSAYISI, 
	   COUNT(BD.ID) ALDIGI_URUN_SAYISI, 
	   SUM(BD.AMOUNT) ALDIGI_URUN_MIKTARI, SUM(TOTAL) ODEDIGI_UCRET
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
INNER JOIN ITEM I ON I.ID=BD.ID
INNER JOIN ORDER_ O ON O.BASKETID=B.ID
INNER JOIN ADDRES A ON A.ID=O.ADDRESSID
INNER JOIN CITY C ON C.ID=A.CITYID
INNER JOIN TOWN T ON T.ID=A.TOWNID
INNER JOIN DISTRICT D ON D.ID=A.DISTRICTID
INNER JOIN INVOICE INV ON INV.ORDERID=O.ID
GROUP BY C.CITY

