SELECT U.USERNAME_, B.CREATEDDATE, BD.AMOUNT, BD.PRICE,
	   BD.TOTAL, I.ITEMCODE, I.ITEMNAME, I.CATEGORY1,
	   I.CATEGORY2, I.CATEGORY3, C.CITY, T.TOWN,
	   D.DISTRICT ,A.ADDRESSTEXT, INV.INVOICENO,
	   INV.CARGOFICHENO, INV.DATE_ SHIPDATE
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
INNER JOIN ITEM I ON I.ID=BD.ID
INNER JOIN ORDER_ O ON O.BASKETID=B.ID
INNER JOIN ADDRES A ON A.ID=O.ADDRESSID
INNER JOIN CITY C ON C.ID=A.CITYID
INNER JOIN TOWN T ON T.ID=A.TOWNID
INNER JOIN DISTRICT D ON D.ID=A.DISTRICTID
INNER JOIN INVOICE INV ON INV.ORDERID=O.ID

