
DECLARE @ISIM AS VARCHAR(50)
SET @ISIM='RECEP'

DECLARE @SAYI AS INTEGER
SET @SAYI=15

DECLARE @SAYI2 AS INTEGER
SET @SAYI2=20

DECLARE @TOPLAM AS INTEGER
SET @TOPLAM=@SAYI+@SAYI2

SELECT @ISIM AS ISIM, @SAYI AS SAYI, @SAYI2 AS SAYI2, @TOPLAM AS TOPLAM


CREATE DATABASE TEST
