
--INSERT INTO SELECT komutu ile WORKERS tablomuzu dolduracagiz.

INSERT INTO WORKERS
([WORKERCODE], [WORKERNAME], [GENDER], [BIRTHDATE], 
[TCNO], [WORKERBARCODE])
SELECT TOP 1000 
TCNO AS WORKERCODE, NAMESURNAME AS WORKERNAME, GENDER, 
BIRTHDATE, TCNO, NEWID() AS WORKERBARCODE
FROM CRM.DBO.CUSTOMERS

SELECT * FROM CRM.DBO.CUSTOMERS