CREATE VIEW VWORDERS
AS

SELECT 
U.USERNAME_ KULLANICIADI,U.NAMESURNAME ADSOYAD,C.COUNTRY ULKE,CT.CITY SEHIR,
T.TOWN ILCE,O.ID,ITM.ITEMCODE,ITM.ITEMNAME,ITM.BRAND MARKA,OD.AMOUNT MIKTAR,
OD.UNITPRICE BIRIMFIYAT,OD.LINETOTAL SATIRTOPLAMI
FROM
ORDERDETAILS OD
JOIN ORDERS O ON OD.ORDERID=O.ID
JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID



SELECT * FROM VWORDERS --View'lar bu sekilde cagirilir.
WHERE KULLANICIADI='M_ALI' --View'larda kolon isimlerini kullanabiliriz.

-------------------------------------------------------------------------
--Yýl ve Aylara gore satis bilgisi
CREATE VIEW VW_AYLARA_GORE_SATISLAR
AS
SELECT 
DATEPART(YEAR,O.DATE_) YIL, DATEPART(MONTH,O.DATE_) AY,
SUM(AMOUNT) TOPLAMMIKTAR, 
SUM(LINETOTAL) TOPLAMSATIS,
COUNT(DISTINCT OD.ID) URUNSAYISI,
COUNT(DISTINCT O.ID) MUSTERISAYISI
FROM
ORDERDETAILS OD
JOIN ORDERS O ON OD.ORDERID=O.ID
JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
GROUP BY DATEPART(YEAR,O.DATE_), DATEPART(MONTH,O.DATE_)

SELECT * FROM VW_AYLARA_GORE_SATISLAR
ORDER BY YIL,AY

---------------------------------------------------------------
SELECT TOP 1000
U.USERNAME_ KULLANICIADI,U.NAMESURNAME ADSOYAD, U.TELNR1,U.TELNR2,
ITM.CATEGORY1, ITM.CATEGORY2, ITM.CATEGORY3, ITM.CATEGORY4,
C.COUNTRY ULKE,CT.CITY SEHIR,
A.ADDRESSTEXT ACIKADRES, O.ID SIPARISID, CONVERT(DATE,O.DATE_) SIPARISTARIHI,
CONVERT(TIME,O.DATE_) SIPARISSAATI,DATEPART(YEAR,O.DATE_) YIL, DATEPART(MONTH,O.DATE_) AY,
T.TOWN ILCE,O.ID,ITM.ITEMCODE URUNKODU,ITM.ITEMNAME URUNADI,ITM.BRAND MARKA,OD.AMOUNT MIKTAR,
OD.UNITPRICE BIRIMFIYAT,OD.LINETOTAL SATIRTOPLAMI
FROM
ORDERDETAILS OD
JOIN ORDERS O ON OD.ORDERID=O.ID
JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
